resources:
  - name: app-image
    type: docker-image
    source:
      repository: killemx/my-app
      username: killemx
      password: 4Whomthebell

  - name: my-app-repo
    type: git
    source:
      uri: https://github.com/pinkyroman/sample.git
      branch: main

jobs:
  - name: build-and-publish
    plan:
      - get: my-app-repo
      - put: app-image
        params:
          build: my-app-repo/app # 빌드 할 Dockerfile을 담고 있는 디렉터리에 대한 경로
          dockerfile: my-app-repo/ci/dockerfiles/app/Dockerfile.prod # Dockefile이 빌드 디렉터리의 루트에 존재하지 않는 경우, Dokerfile에 대한 경로.
          tag_file: my-app-repo/VERSION
          tag_as_latest: true
